'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Match={id:string;title:string;mode:string;map:string;fee:number;prize:number;slots:number;filled:number;time:string;roomId:string;roomPassword:string;status:'UPCOMING'|'ROOM READY'|'LIVE'|'COMPLETED'};
const defaults:Match[]=[
{id:'m1',title:'Clash Squad 4v4 Cup',mode:'CS 4v4',map:'Bermuda',fee:40,prize:600,slots:8,filled:0,time:'Today 10:00 PM',roomId:'',roomPassword:'',status:'UPCOMING'},
{id:'m2',title:'Bermuda Grand Championship',mode:'Squad',map:'Bermuda',fee:100,prize:2500,slots:48,filled:0,time:'Tomorrow 8:00 PM',roomId:'',roomPassword:'',status:'UPCOMING'},
{id:'m3',title:'Purgatory Solo Rush',mode:'Solo',map:'Purgatory',fee:30,prize:1000,slots:48,filled:0,time:'Tomorrow 10:30 PM',roomId:'',roomPassword:'',status:'UPCOMING'}];
const KEY='zaid_ff_matches_v2'; const SITE='zaid_ff_site_online_v2';
export default function Home(){const [matches,setMatches]=useState<Match[]>(defaults);const [online,setOnline]=useState(true);useEffect(()=>{try{const m=localStorage.getItem(KEY);if(m)setMatches(JSON.parse(m));const s=localStorage.getItem(SITE);if(s)setOnline(s==='1')}catch{}},[]);if(!online)return <><Nav/><main className="wrap"><div className="hero"><h1>ZAID FF is Offline</h1><p>Tournament registrations are temporarily closed by the organizer.</p><Link className="btn" href="/admin">Open Admin Panel</Link></div></main></>;return <><Nav/><main className="wrap"><section className="hero"><span className="badge">● ONLINE • FREE FIRE ESPORTS</span><h1>ZAID <span style={{color:'#ffbd00'}}>FF</span> TOURNAMENT</h1><p>Official Free Fire tournament hub — matches, rooms, slots and prizes.</p><div className="actions"><a className="btn primary" href="#tournaments">View Tournaments</a><Link className="btn" href="/admin">Admin Panel</Link></div></section><section className="section"><div className="grid"><div className="card"><div className="muted">ACTIVE TOURNAMENTS</div><div className="stat">{matches.filter(x=>x.status!=='COMPLETED').length}</div></div><div className="card"><div className="muted">PRIZE POOL</div><div className="stat">Rs. {matches.reduce((a,x)=>a+x.prize,0)}</div></div><div className="card"><div className="muted">SUPPORT</div><div className="stat">03302475360</div></div></div></section><section className="section" id="tournaments"><h2>🔥 Live & Upcoming Tournaments</h2><div className="grid">{matches.map(m=><div className="card" key={m.id}><span className="badge">{m.status}</span><h3>{m.title}</h3><p className="muted">{m.mode} • {m.map} • {m.time}</p><div className="price">Rs. {m.prize}</div><p className="muted">Entry Rs. {m.fee} • {m.filled}/{m.slots} slots</p>{m.roomId&&<div className="notice">Room ID: <b>{m.roomId}</b><br/>Password: <b>{m.roomPassword}</b></div>}<div className="actions"><button className="btn primary" onClick={()=>alert(`Registration for ${m.title} is ready. Contact 03302475360 to confirm your slot.`)}>Register Now</button></div></div>)}</div></section></main><Footer/></>}
function Nav(){return <header className="nav"><div className="navin"><div className="brand">ZAID <span>FF</span></div><div className="links"><a className="link" href="#tournaments">Tournaments</a><a className="link" href="#tournaments">Leaderboard</a><Link className="link" href="/admin">👑 Admin</Link></div></div></header>}
function Footer(){return <footer className="footer">© {new Date().getFullYear()} ZAID FF Tournament • Free Fire Battle Royale & CS Hub</footer>}
